# Generated by Django 2.2.3 on 2019-08-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publishedDate', models.DateField(verbose_name='publishedDates')),
                ('industryIndentifiers', models.CharField(max_length=250)),
                ('pageCount', models.PositiveIntegerField()),
                ('imageLinks', models.URLField(verbose_name='imagesLinks')),
                ('language', models.TextField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Authors', to='book.Author')),
            ],
        ),
    ]
